name: Build Packages
on:
  workflow_dispatch:

jobs:
  package-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cake publish script
        uses: cake-build/cake-action@v1
        with:
          target: PublishWindows
      - name: Rename executable
        run: Rename-Item -Path "CPCSharp.Avalonia/bin/Release/net5.0-windows/win-x64/publish/CPCSharp.Avalonia.exe" -NewName "CPCSharp.exe"
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows Executable
          path: CPCSharp.Avalonia/bin/Release/net5.0-windows/win-x64/publish/CPCSharp.exe
  package-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Import codesigning certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.DEVELOPER_ID_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.DEVELOPER_ID_CERTIFICATE_P12_PASSWORD }}
      - name: Cake publish script
        uses: cake-build/cake-action@v1
        with:
          target: PublishMac
      - name: "Notarize Release Build"
        uses: devbotsxyz/xcode-notarize@v1
        with:
          product-path: BuildArtifacts/CPC#.app
          appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}
      - name: "Staple Release Build"
        uses: devbotsxyz/xcode-staple@v1
        with:
          product-path: BuildArtifacts/CPC#.app
          verbose: true
      - name: Zip App Bundle
        run: ditto -V -c -k --keepParent BuildArtifacts/CPC#.app BuildArtifacts/CPC#.zip
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macOS Executable
          path: BuildArtifacts/CPC#.zip
